#!/usr/bin/env python3
"""A generated contents block for a long document, so a fact can be found by looking.

    python3 tools/doc-index.py --publish       # rewrite every opted-in doc
    python3 tools/doc-index.py --check         # fail if any is behind

WHY. docs/shortcuts-format-notes.md is 16,000 words in 50 sections appended in
the order each thing was discovered. Every heading is already a claim in a
sentence ("Control flow is three actions sharing a UUID"), which means the
headings alone are a usable lookup table and nothing was assembling them. A
reader who had not read the file before found a fact by reading the file, and a
session with the file in context re-derived things it already held.

This adds no prose. It lists what the document already says it covers, which is
the cheapest structure a 16,000-word log can carry, and it is generated, so it
cannot drift into claiming a section that was renamed or removed.

OPT IN BY MARKER, NEVER BY GUESS. A document joins by carrying the two marker
comments; nothing here decides where an index belongs in a file it did not
write. A doc listed below without the markers is reported, not repaired.

The anchors follow GitHub's own slug rules, since these links are read on
GitHub: lowercase, punctuation dropped, spaces to hyphens, and a numeric suffix
on a repeat. A slug this gets wrong is a link that scrolls nowhere, which is the
one way a contents block is worse than none.
"""
import argparse, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ["docs/shortcuts-format-notes.md", "workflows/README.md"]
OPEN, CLOSE = "<!-- doc-index -->", "<!-- /doc-index -->"


def slug(title, seen):
    s = re.sub(r"`", "", title)
    s = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", s)        # a link reads as its text
    s = s.lower()
    s = re.sub(r"[^\w\- ]", "", s, flags=re.UNICODE).strip()
    s = s.replace(" ", "-")
    n = seen.get(s, 0)
    seen[s] = n + 1
    return s if n == 0 else f"{s}-{n}"


def headings(text):
    """Every ## and ### below the index block, in document order.

    Headings inside a fenced code block are not headings, and this repo's docs
    are full of fenced chain listings whose comment lines start with #.
    """
    out, fenced = [], False
    for line in text.split("\n"):
        if line.startswith("```"):
            fenced = not fenced
            continue
        if fenced:
            continue
        m = re.match(r"^(#{2,3})\s+(.+?)\s*$", line)
        if m:
            out.append((len(m.group(1)), m.group(2)))
    return out


def block(text):
    seen, rows = {}, []
    for level, title in headings(text):
        anchor = slug(title, seen)
        rows.append(("  " * (level - 2)) + f"- [{title}](#{anchor})")
    return "\n".join([OPEN,
                      f"**{len(rows)} sections.** Generated by `python3 tools/doc-index.py --publish`.",
                      "",
                      *rows,
                      CLOSE])


def rewrite(path):
    text = path.read_text()
    if OPEN not in text or CLOSE not in text:
        return None
    head, rest = text.split(OPEN, 1)
    _, tail = rest.split(CLOSE, 1)
    # Built from the document WITHOUT its old block, so a stale row can never
    # index itself into the next run.
    return head + block(head + tail) + tail


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("docs", nargs="*", help="default: the opted-in list")
    ap.add_argument("--publish", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    behind, unmarked = [], []
    for rel in (args.docs or DOCS):
        path = ROOT / rel
        want = rewrite(path)
        if want is None:
            unmarked.append(rel)
            continue
        if want == path.read_text():
            continue
        behind.append(rel)
        if args.publish:
            path.write_text(want)

    for rel in unmarked:
        print("no %s marker, skipped: %s" % (OPEN, rel), file=sys.stderr)
    if args.check:
        if behind:
            print("behind: %s; run: python3 tools/doc-index.py --publish" % ", ".join(behind),
                  file=sys.stderr)
            raise SystemExit(1)
        print("every opted-in doc index is current", file=sys.stderr)
        return
    if args.publish:
        print("rewrote %d of %d" % (len(behind), len(args.docs or DOCS)), file=sys.stderr)


if __name__ == "__main__":
    main()
