#!/usr/bin/env python3
"""The recurrence index at the top of docs/SNAGS.md.

    python3 tools/snags-index.py --publish
    python3 tools/snags-index.py --check

WHY A COUNT AND NOT A DIARY. The log's rule is that recurrence is the signal: one
trip is noise, the same trip three times earns a fix that removes the cause. That
rule needs the set to be visible at the moment of appending, because a session
that trips over something opens this file, reads the header, and writes at the
top. It does not read 300 lines of entries first. So the index sits between the
header and the newest entry, sorted by count, and the repeat offenders lead.

Counting by hand is the thing that cannot work: a hand count is exactly the
number a session will get wrong, and a wrong count in the place that claims to
measure repetition is worse than no count. So it is derived, and --check holds
it, the same contract packed/, plists/ and catalog.json each run.

WHAT IT PARSES, STRICTLY. An entry is `## <slug>` followed by a one-line
summary, then a `seen:` line of ISO dates, each optionally carrying `xN` for a
day that tripped more than once. Anything else on a seen line is reported rather
than counted, because web-tools' log learned that the hard way: a sighting list
written as prose turned three stray commas into three sightings and one entry
read x8 against a true x1.
"""
import argparse, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOG = ROOT / "docs" / "SNAGS.md"
OPEN, CLOSE = "<!-- snags-index -->", "<!-- /snags-index -->"
SIGHTING = re.compile(r"^(\d{4}-\d{2}-\d{2})(?:\s*[x×](\d+))?$")


def entries(text):
    out, cur, bad = [], None, []
    for line in text.split("\n"):
        m = re.match(r"^##\s+`?([a-z0-9-]+)`?\s*$", line)
        if m:
            cur = {"slug": m.group(1), "summary": "", "dates": [], "count": 0}
            out.append(cur)
            continue
        if cur is None:
            continue
        if line.startswith("seen:"):
            for part in line[len("seen:"):].split(","):
                part = part.strip()
                if not part:
                    continue
                s = SIGHTING.match(part)
                if not s:
                    bad.append((cur["slug"], part))
                    continue
                cur["dates"].append(s.group(1))
                cur["count"] += int(s.group(2) or 1)
        elif not cur["summary"] and line.strip() and not line.startswith("→"):
            cur["summary"] = line.strip()
    return out, bad


def block(items):
    items = sorted(items, key=lambda e: (-e["count"], max(e["dates"] or [""])), reverse=False)
    rows = ["| snag | last seen | what it was |", "| --- | --- | --- |"]
    for e in items:
        mult = f" **x{e['count']}**" if e["count"] > 1 else ""
        rows.append("| `%s`%s | %s | %s |"
                    % (e["slug"], mult, max(e["dates"]) if e["dates"] else "?", e["summary"]))
    trips = sum(e["count"] for e in items)
    return "\n".join([
        OPEN,
        f"**{len(items)} snags, {trips} trips**, repeats first. Read this before adding one: a trip",
        "already here belongs in the entry that owns it, as another date on its `seen:` line, not as",
        "a second entry. Generated by `python3 tools/snags-index.py --publish`.",
        "",
        *rows,
        CLOSE])


def rewrite():
    text = LOG.read_text()
    head, rest = text.split(OPEN, 1)
    _, tail = rest.split(CLOSE, 1)
    items, bad = entries(head + tail)
    return head + block(items) + tail, bad


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--publish", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    want, bad = rewrite()
    for slug, part in bad:
        print("not a sighting, not counted: %s -> %r" % (slug, part), file=sys.stderr)
    if args.check:
        if want != LOG.read_text():
            print("docs/SNAGS.md index is behind; run: python3 tools/snags-index.py --publish",
                  file=sys.stderr)
            raise SystemExit(1)
        print("the snags index is current", file=sys.stderr)
        return
    if args.publish:
        LOG.write_text(want)
        print("wrote the snags index", file=sys.stderr)
        return
    sys.stdout.write(want)


if __name__ == "__main__":
    main()
